version: "0.0.1"

services:
  nginx-test-web-app:
    container_name: nginx-test-web-app
    image: nginx-test-web-app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - ./log:/var/log/nginx/
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html/
    networks:
      - networks-host

networks:
  networks-host:
    driver: bridge